'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30128.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MigAssistant.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.07.
        '''</summary>
        Friend ReadOnly Property appBuild() As String
            Get
                Return ResourceManager.GetString("appBuild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to www.dcunningham.net.
        '''</summary>
        Friend ReadOnly Property appCompany() As String
            Get
                Return ResourceManager.GetString("appCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to www.microsoft.com.
        '''</summary>
        Friend ReadOnly Property appNetworkPingCheck() As String
            Get
                Return ResourceManager.GetString("appNetworkPingCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Workstation Migration Assistant.
        '''</summary>
        Friend ReadOnly Property appTitle() As String
            Get
                Return ResourceManager.GetString("appTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.dcunningham.net.
        '''</summary>
        Friend ReadOnly Property appWebsite() As String
            Get
                Return ResourceManager.GetString("appWebsite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error was encountered while trying to open the Advanced Settings Dialog Box.
        '''</summary>
        Friend ReadOnly Property backupAdvancedSettingsProcessException() As String
            Get
                Return ResourceManager.GetString("backupAdvancedSettingsProcessException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ComponentList.XML.
        '''</summary>
        Friend ReadOnly Property bddComponentFile() As String
            Get
                Return ResourceManager.GetString("bddComponentFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BDDManifest.Cab.
        '''</summary>
        Friend ReadOnly Property bddManifestFile() As String
            Get
                Return ResourceManager.GetString("bddManifestFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://go.microsoft.com/fwlink/?LinkId=104379.
        '''</summary>
        Friend ReadOnly Property bddManifestURL() As String
            Get
                Return ResourceManager.GetString("bddManifestURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an error while determining the path of the existing datastore.
        '''</summary>
        Friend ReadOnly Property datastoreDetectionError() As String
            Get
                Return ResourceManager.GetString("datastoreDetectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multiple migration folders detected, but none was selected!.
        '''</summary>
        Friend ReadOnly Property datastoreMultipleFoundNoneSelected() As String
            Get
                Return ResourceManager.GetString("datastoreMultipleFoundNoneSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to find migration datastore for the current user.
        '''</summary>
        Friend ReadOnly Property datastoreNotFound() As String
            Get
                Return ResourceManager.GetString("datastoreNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have opted not to repair the errors on your Hard Disk. You may encounter problems during the data capture!.
        '''</summary>
        Friend ReadOnly Property diskScanFixCancelledMessage() As String
            Get
                Return ResourceManager.GetString("diskScanFixCancelledMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Errors have been discovered on your Hard Disk. In order to fix these errors, Windows needs to restart to enter a special error fixing mode. This may take a long time to complete. Select Yes to fix the problem, No to continue with the migration without fixing, or Cancel to exit the application.
        '''</summary>
        Friend ReadOnly Property diskScanFixMessage() As String
            Get
                Return ResourceManager.GetString("diskScanFixMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to % Complete.
        '''</summary>
        Friend ReadOnly Property diskScanPercent() As String
            Get
                Return ResourceManager.GetString("diskScanPercent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while trying to perform the Hard Disk Health Check..
        '''</summary>
        Friend ReadOnly Property diskScanProcessException() As String
            Get
                Return ResourceManager.GetString("diskScanProcessException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Errors Found.
        '''</summary>
        Friend ReadOnly Property diskScanResultErrors() As String
            Get
                Return ResourceManager.GetString("diskScanResultErrors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Hard Disk Health Check is complete and no errors have been discovered.
        '''</summary>
        Friend ReadOnly Property diskScanResultOk() As String
            Get
                Return ResourceManager.GetString("diskScanResultOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Errors Found.
        '''</summary>
        Friend ReadOnly Property diskScanResultOk1() As String
            Get
                Return ResourceManager.GetString("diskScanResultOk1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you decide to bypass the Hard Disk Health Check, you may encounter problems during the migration!.
        '''</summary>
        Friend ReadOnly Property diskScanSkippedMessage() As String
            Get
                Return ResourceManager.GetString("diskScanSkippedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verifying Files....
        '''</summary>
        Friend ReadOnly Property diskScanStatus1() As String
            Get
                Return ResourceManager.GetString("diskScanStatus1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verifying Indexes....
        '''</summary>
        Friend ReadOnly Property diskScanStatus2() As String
            Get
                Return ResourceManager.GetString("diskScanStatus2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verifying Security Descriptors....
        '''</summary>
        Friend ReadOnly Property diskScanStatus3() As String
            Get
                Return ResourceManager.GetString("diskScanStatus3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unknown error occurred while trying to perform the Hard Disk Health Check..
        '''</summary>
        Friend ReadOnly Property diskScanUnknownError() As String
            Get
                Return ResourceManager.GetString("diskScanUnknownError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The specified encryption keys do not match! Please re-enter both keys..
        '''</summary>
        Friend ReadOnly Property encryptionKeysDontMatch() As String
            Get
                Return ResourceManager.GetString("encryptionKeysDontMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You did not specify a custom encryption key. The standard encryption key will be used..
        '''</summary>
        Friend ReadOnly Property encryptionNoKeySpecified() As String
            Get
                Return ResourceManager.GetString("encryptionNoKeySpecified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.
        '''</summary>
        Friend ReadOnly Property exitCodeCMDLineParamError() As String
            Get
                Return ResourceManager.GetString("exitCodeCMDLineParamError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend ReadOnly Property exitCodeMigrationFailed() As String
            Get
                Return ResourceManager.GetString("exitCodeMigrationFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.
        '''</summary>
        Friend ReadOnly Property exitCodeOk() As String
            Get
                Return ResourceManager.GetString("exitCodeOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend ReadOnly Property exitCodePostMigrationScriptFail() As String
            Get
                Return ResourceManager.GetString("exitCodePostMigrationScriptFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend ReadOnly Property exitCodePreMigrationScriptFail() As String
            Get
                Return ResourceManager.GetString("exitCodePreMigrationScriptFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.
        '''</summary>
        Friend ReadOnly Property exitCodeUSMTNotFoundError() As String
            Get
                Return ResourceManager.GetString("exitCodeUSMTNotFoundError", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property imageIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("imageIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property imageTitle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageTitle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attached are the migration details for the above user and workstation..
        '''</summary>
        Friend ReadOnly Property mailMessage() As String
            Get
                Return ResourceManager.GetString("mailMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Collecting data for user:.
        '''</summary>
        Friend ReadOnly Property migrationCollectingUser() As String
            Get
                Return ResourceManager.GetString("migrationCollectingUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The migration failed with a fatal error:.
        '''</summary>
        Friend ReadOnly Property migrationCompleteError() As String
            Get
                Return ResourceManager.GetString("migrationCompleteError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The migration has been completed successfully..
        '''</summary>
        Friend ReadOnly Property migrationCompleteSuccess() As String
            Get
                Return ResourceManager.GetString("migrationCompleteSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while trying to delete the existing Migration data:.
        '''</summary>
        Friend ReadOnly Property migrationDeleteExistingError() As String
            Get
                Return ResourceManager.GetString("migrationDeleteExistingError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Included Users:.
        '''</summary>
        Friend ReadOnly Property migrationDetectedUser() As String
            Get
                Return ResourceManager.GetString("migrationDetectedUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The migration process did not complete successfully..
        '''</summary>
        Friend ReadOnly Property migrationFailedMessage() As String
            Get
                Return ResourceManager.GetString("migrationFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Migration Failed..
        '''</summary>
        Friend ReadOnly Property migrationFailedStatus() As String
            Get
                Return ResourceManager.GetString("migrationFailedStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The specified Migration server cannot be used as there is no network connection available, or the server cannot be contacted..
        '''</summary>
        Friend ReadOnly Property migrationFindServerFailText() As String
            Get
                Return ResourceManager.GetString("migrationFindServerFailText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to connect to server:.
        '''</summary>
        Friend ReadOnly Property migrationFindServerFailTitle() As String
            Get
                Return ResourceManager.GetString("migrationFindServerFailTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Included components:.
        '''</summary>
        Friend ReadOnly Property migrationForUser() As String
            Get
                Return ResourceManager.GetString("migrationForUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The amount of data to be migrated exceeds the maximum allowed size. Please remove any unnecessary data and try again..
        '''</summary>
        Friend ReadOnly Property migrationMaxSizeExceededError() As String
            Get
                Return ResourceManager.GetString("migrationMaxSizeExceededError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of non-fatal errors:.
        '''</summary>
        Friend ReadOnly Property migrationNonFatalErrors() As String
            Get
                Return ResourceManager.GetString("migrationNonFatalErrors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Migration data already exists at the migration location. Do you want to overwrite it?.
        '''</summary>
        Friend ReadOnly Property migrationOverwriteExistingFolder() As String
            Get
                Return ResourceManager.GetString("migrationOverwriteExistingFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restoring data....
        '''</summary>
        Friend ReadOnly Property migrationPhaseApplying() As String
            Get
                Return ResourceManager.GetString("migrationPhaseApplying", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generating data collection information....
        '''</summary>
        Friend ReadOnly Property migrationPhaseCollecting() As String
            Get
                Return ResourceManager.GetString("migrationPhaseCollecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estimating migration size....
        '''</summary>
        Friend ReadOnly Property migrationPhaseEstimating() As String
            Get
                Return ResourceManager.GetString("migrationPhaseEstimating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initialising....
        '''</summary>
        Friend ReadOnly Property migrationPhaseInitializing() As String
            Get
                Return ResourceManager.GetString("migrationPhaseInitializing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capturing data....
        '''</summary>
        Friend ReadOnly Property migrationPhaseSaving() As String
            Get
                Return ResourceManager.GetString("migrationPhaseSaving", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanning for data to migrate....
        '''</summary>
        Friend ReadOnly Property migrationPhaseScanning() As String
            Get
                Return ResourceManager.GetString("migrationPhaseScanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error was encountered while running Post-Migration Support Scripts.
        '''</summary>
        Friend ReadOnly Property migrationPostMigrationScriptFail() As String
            Get
                Return ResourceManager.GetString("migrationPostMigrationScriptFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error was encountered while running Pre-Migration Support Scripts.
        '''</summary>
        Friend ReadOnly Property migrationPreMigrationScriptFail() As String
            Get
                Return ResourceManager.GetString("migrationPreMigrationScriptFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Migration Completed Successfully..
        '''</summary>
        Friend ReadOnly Property migrationSuccessStatus() As String
            Get
                Return ResourceManager.GetString("migrationSuccessStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must agree to the terms and conditions before you can start the Migration..
        '''</summary>
        Friend ReadOnly Property migrationTermsCheckFail() As String
            Get
                Return ResourceManager.GetString("migrationTermsCheckFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minutes remaining.
        '''</summary>
        Friend ReadOnly Property migrationTotalMinutesRemaining() As String
            Get
                Return ResourceManager.GetString("migrationTotalMinutesRemaining", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to % Complete.
        '''</summary>
        Friend ReadOnly Property migrationTotalPercentageCompleted() As String
            Get
                Return ResourceManager.GetString("migrationTotalPercentageCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MB to transfer.
        '''</summary>
        Friend ReadOnly Property migrationTotalSizeInMBToTransfer() As String
            Get
                Return ResourceManager.GetString("migrationTotalSizeInMBToTransfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to has been connected..
        '''</summary>
        Friend ReadOnly Property usbDeviceConnectedEvent() As String
            Get
                Return ResourceManager.GetString("usbDeviceConnectedEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is connected..
        '''</summary>
        Friend ReadOnly Property usbDeviceConnectedStartup() As String
            Get
                Return ResourceManager.GetString("usbDeviceConnectedStartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A USB Disk Drive.
        '''</summary>
        Friend ReadOnly Property usbDeviceDescription() As String
            Get
                Return ResourceManager.GetString("usbDeviceDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An additional USB Disk Drive.
        '''</summary>
        Friend ReadOnly Property usbDeviceDescriptionAdditional() As String
            Get
                Return ResourceManager.GetString("usbDeviceDescriptionAdditional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The USB Disk Drive.
        '''</summary>
        Friend ReadOnly Property usbDeviceDescriptionCurrent() As String
            Get
                Return ResourceManager.GetString("usbDeviceDescriptionCurrent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to has been disconnected..
        '''</summary>
        Friend ReadOnly Property usbDeviceDisconnectedEvent() As String
            Get
                Return ResourceManager.GetString("usbDeviceDisconnectedEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to However, the SMART Status of the drive shows that it is not operating within normal tolerences..
        '''</summary>
        Friend ReadOnly Property usbDeviceSMARTFail1() As String
            Get
                Return ResourceManager.GetString("usbDeviceSMARTFail1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In order to protect against accidental data loss due to a corruption or drive failure, you cannot use this drive for a migration..
        '''</summary>
        Friend ReadOnly Property usbDeviceSMARTFail2() As String
            Get
                Return ResourceManager.GetString("usbDeviceSMARTFail2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The default migration location will be used instead..
        '''</summary>
        Friend ReadOnly Property usbDeviceSwitchToStandard() As String
            Get
                Return ResourceManager.GetString("usbDeviceSwitchToStandard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to use this drive for the migration process?.
        '''</summary>
        Friend ReadOnly Property usbDeviceUseDrive() As String
            Get
                Return ResourceManager.GetString("usbDeviceUseDrive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {863E4C66-38D1-4288-8A68-356FC8543E08}.
        '''</summary>
        Friend ReadOnly Property usmtGUIDx64() As String
            Get
                Return ResourceManager.GetString("usmtGUIDx64", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0707EA8E-A2AF-42c4-86A8-95332FDF1E3D}.
        '''</summary>
        Friend ReadOnly Property usmtGUIDx86() As String
            Get
                Return ResourceManager.GetString("usmtGUIDx86", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This application requires the Microsoft User State Migration Tool to be installed. Click Ok to start downloading, or Cancel to exit the application.
        '''</summary>
        Friend ReadOnly Property usmtNotFoundError() As String
            Get
                Return ResourceManager.GetString("usmtNotFoundError", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
